### ISSUE TITLE
What order are scripts run in the pipeline?

### ISSUE THREAD

**Issue by josephmje** [TIGRLab/datman#116]
I was looking at `tigrlab_config.yaml` in the assets directory but it seems to be out of date. Some of the scripts under PipelineSettings are missing and I'm assuming have been replaced with others.

Thanks,
Michael

**Comment by DESm1th** [comment]
Hi Michael,

The PipelineSettings in tigrlab_config.yaml are not used anywhere. They were phased out about two years ago. I've deleted them recently but havent pushed the changes yet. The *_management.sh and *_analysis.sh scripts that are on our filesystem for each study are the exact pipelines we run.

**Comment by josephmje** [comment]
Thanks Dawn,

Are any of the scripts that are currently run up on Github? Do you have a list of the order they are run in? I'm interested in using DATMAN's QC features and dashboard on a dataset.

**Comment by DESm1th** [comment]
Oh! Sorry, I assumed you had access to our file system since we dont often get questions from external people. 

Ok, brace yourself this is going to be a long one (and maybe more detail than you need). Here is the exact bash script we run as a cron job for one of our studies (SPINS)

```#!/bin/bash -l

export STUDYNAME=SPINS         # /archive/data/${STUDYNAME}
export PYTHONWARNINGS="ignore" # suppresses warnings from pydicom, etc
module load SGE-extras
module load /archive/code/packages.module
source activate

function message () { echo "$(date): $1"; }
{
  message "Running pipelines for study: $STUDYNAME"

  message "Deleting blacklisted scans..."
  dm_blacklist_rm.py -q $STUDYNAME

  message "Get new scans..."
  dm_sftp.py -q $STUDYNAME

  message "Link scans..."
  dm_link.py -q $STUDYNAME

  message "Uploading new scans to XNAT..."
  dm_xnat_upload.py -q $STUDYNAME

  message "Extract new scans from XNAT..."
  (
  module load slicer/4.4.0 minc-toolkit/1.0.01
  dm_xnat_extract.py -q $STUDYNAME
  )

  message "Updating shared subject IDs in XNAT and making links..."
  dm_link_shared_ids.py -q $STUDYNAME

  message "Split the PDT2 images..."
  (
  module load FSL/5.0.10
  dm_proc_split_pdt2.py -q $STUDYNAME
  )

  message "Generate QC reports..."
  (
  module load matlab/R2014a AFNI/2014.12.16 FSL/5.0.10
  dm_qc_report.py --log-to-server $STUDYNAME
  )

  message "Updating dashboard..."
  parse_qc.py $STUDYNAME

  message "Updating demographic data..."
  redcap_demographics.py $STUDYNAME

} | tee -a /archive/logs/run-all-$STUDYNAME-$(date +%Y%m%d).log
```
A lot of the steps can be run individually and often can be run out of order as long as our file system structure is in place (We have some [documentation up here](https://github.com/TIGRLab/documentation/wiki/Data-Organization). Some other pages on that wiki may be useful as well.). The steps with additional dependencies should run just fine with newer versions of the listed software, as well.

In general, the core data management pipeline (in order) is: 

1. dm_sftp.py    -> Grabs new scans from the configured MR server (can be skipped, if you have some other way of getting the data onto your system)

2. dm_link.py    -> Attempts to read the correct naming scheme from the 'PatientName' field of the headers and makes links with the correct naming scheme that point to the original zip files. These correctly named files are then used for all future stages. It can also read a 'scans.csv' file to manually set what the naming scheme should be. This step can be skipped entirely if you have already some way of imposing a datman-style naming scheme on your data. Using another naming scheme will likely require a lot of modification to our code since a lot of our code will exit if something is 'misnamed' (i.e. doesnt match the expected STUDY_SITE_SUBID_TIMEPOINT#_REPEAT# scheme). 

3. dm_xnat_upload.py  -> Uploads the correctly named data to the configured xnat server. Can be skipped if you're not using xnat, obviously.

4. dm_xnat_extract.py  -> Downloads all new data found on XNAT and converts it to the configured file formats. This step is mostly useful if you have multi-site data, as we do, since our other sites just upload directly to XNAT instead of adding data to our MR server. Again, skippable if you have your own set up for converting your data and setting up our expected file structure.

5. dm_linked_shared_ids.py  -> This step is only run because we have some scans that are shared between studies, under multiple ids. This just makes symbolic links and keeps a record of what was linked where in the study metadata folder.

6. dm_proc_split_pdt2.py   -> Splits all discovered PDT2 files into separate files tagged PD and T2 for ease of use later on.

7. dm_qc_report.py  -> Generates html QC pages from the data found in the STUDY/data/nii and STUDY/data/dcm folders. These get linked to on the dashboard if you're using both datman and the dashboard, or can be used independently.

8. parse_qc.py  -> Not required if you're not using the dashboard too. It just finds new qc files generated by qc_report and adds them to the dashboard's postgres database

9. redcap_demographics.py  -> this one is pretty specific to our study (SPINS) but can serve as a good template if you use redcap to hold any study related data and want to automate pulling it down in regular reports for quality control.

So depending on how you have your data set up, if you're only interested QC you can probably write a few bash scripts to move (or link) your data into our expected structure and naming scheme and then just run dm_qc_report and parse_qc to get the dashboard and html pages working.

Let me know if you run into any problems, especially with regards to dashboard set up. Our documentation on that is a little shaky still.

**Comment by josephmje** [comment]
Sorry for the confusion Dawn. Thanks for the level of detail! 

I've already got a slightly different method of anonymizing and uploading data to an XNAT database so perhaps I'll stick with that. It looks like all I'll need is to rename the files and run dm_qc_report.

Thanks for all your help! Yes, eventually I'd like the get the dashboard set up.
