### ISSUE TITLE
QC doesn't update PDF if a repeat scan occurs

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/datman#17]
For instance in the ASDD study AEF015_01_01 was used to generate a QC doc, but then when AEF015_01_02 was acquired, the QC doc was not updated. 

The workaround is to remove the qc pdf and rerun. 

The fix could either be:
 1. detect a repeat and update the QC doc
 2. Output a QC doc for each repeat (not try to collapse them down into a doc for each timepoint). 

I vote for option 2.

**Comment by josephdviviano** [comment]
If you look at how the code is structured #2 is a huge engineering effort, and #1 makes more sense from a management POV (since in the filesystem we are collapsing down to the session level, we do not retain timepoint information),

I suggest we stick with #1 or, if we really want to spend our time doing this, create some sort of database (or use a number in the filename) that keeps track of the number of sessions in each PDF and clobbers them if we have more repeats on the disk than we do in the PDF.

I'm going to vote #1 because this is pretty much a non-issue as far as getting the job done is concerned.

**Comment by pipitone** [comment]
I'm looking at [qc.py](https://github.com/TIGRLab/datman/blob/master/bin/qc.py). It doesn't look like a huge amount of work actually. The `qc_folder()` function would need to make a list of all the repeats in a folder (easy: glob + extract full scan name + uniq), and then handle each repeat separately when creating the pdfs. No? 

Can you explain more about how you see this as a non-issue? Somehow we have to handle the situation where a repeat scan arrives after a qc doc has been created for earlier repeats. What do you propose?

**Comment by josephdviviano** [comment]
Hmm you might be right. I'm thinking more about how the code uses the filenames to determine things about the scan post qc_folder(), but I might not be remembering the structure of the program properly.

I was thinking that manually deleting the pdfs might be a good practice so that we are consciously managing these files, but i guess it isnt because watqc won't detect if we fail to QC a repeat. 

I'll look at the qc_folder() function when I return.

**Comment by pipitone** [comment]
This is done in the new HTML qc pages.
