### ISSUE TITLE
SPINS: dtifitqc error

### ISSUE THREAD

**Issue by josephdviviano** [TIGRLab/datman#29]
Thu Sep 17 10:45:34 EDT 2015: Running ditfit qc...
    FSLDIR environment variable is undefined. Try again.

@edickie, could you comment on why this variable needs to be defined and why this error is being thrown? FSL/5.0.7 is loaded when this command is run.

**Comment by edickie** [comment]
I think it's not defined it the dtifit qc is being run outside the curly
brackets {} were FSL is loaded....

move "module load FSL/5.0.7" to the line directly above dtifit and it
works...

**Comment by pipitone** [comment]
This has been resolved. The issue was an interesting one so I'll document it here for posterity. 

The run script was doing something like this:
```sh
{ 
   module load FSL
   # run commands depending on FSL
} | tee log.txt
# commands depending on FSL but failing because FSL wasn't loaded
```

Usually braces `{ }` in BASH are just used to create lists of statements, and those statements should run in the shell's environment (i.e. not a subshell) so modules loaded inside the braces *will* be loaded after the braces. 

.... except when you redirect the output of the list as we were doing to capture the output and put it in a log file. In that case, it seems BASH *does* create a subshell, which explains why our modules were not loaded afterwards.
