### ISSUE TITLE
Push QC docs to XNAT instead of github? 

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/datman#33]
@edickie suggested that since XNAT has ability to handle QC info, perhaps we could be pushing these docs to XNAT also/instead of github.

**Comment by josephdviviano** [comment]
This is true, but unless I'm missing something about how XNAT works, it won't be very easy for the users.

What might be better is, if we move to a html-only solution, we host the QC online ala: http://imaging-genetics.camh.ca/spins/adni.html

I agree that github has been a bad solution for the end users, though, because they seem to be intimidated by it.
