### ISSUE TITLE
dm-check-headers doesn't handle PDT2 correctly

### ISSUE THREAD

**Issue by pipitone** [TIGRLab/datman#37]
It appears that PDT2 scans contain two sets of dicom files with different headers: one for the PD scan and one for the T2 scan. At the moment, `dm-check-headers` can only handle a single dicom file per tag in the gold standards, so we have no way to properly check these types of scans. 

I suggest: 
1. Add a `--ignore-tags` option to `dm-check-headers` so that we can use it to ignore `PDT2` scans.
2. When we split PDT2 scans, we also create a `PD` and `T2` dicom files in `data/dcm`
3. Add gold standards for `PD` and `T2` to `gold-standards/` in all of our projects. 

Thoughts? 

I'm currently updating `dm-check-headers` so whatever the solution, we should wait until my changes are integrated to fix this issue.

**Comment by josephdviviano** [comment]
This is annoying. I vote for ignore since this is secondary data.

I dont think that the headers for these files are ever going to be consistent ... I'm not sure if the header matches the image it is associated with (so either index 1 or 2 along the 4th dimension) so if we sort the files before copying, we might be able to find one dicom from each image type, but there isn't a guarantee the headers will be different.
