### ISSUE TITLE
write some quick way to commit run script changes

### ISSUE THREAD

**Issue by edickie** [TIGRLab/datman#57]
tigr-write-runsh.py can re-write all the run scripts for all projects in a standardized way.. but it doesn't commit the changes to each project's git repo.

Maybe we just need a little bash script to loop over projects and commit the run-script change to each one...

Or we could build this functionality right into tigr-write-runsh.py

**Comment by josephdviviano** [comment]
Hey @edickie if we have code automatically syncing all of the run scripts, do we need to bother version controlling them at all?

Seems like, if we wanted a history of how the system is set up, we could simply version control the `.yaml` file that `write-runsh.py` reads. That could be done manually.

Looping in @djoverton and @DESm1th for their thoughts.

**Comment by josephdviviano** [comment]
PS the advantage here is removing all git calls from all of the run scripts, which will clean up the logs a lot with very little effort. I don't see much value in the git commits being in the run log because we gitignore almost the entire data folder, and changes to files in `metadata` or whatever are very unlikely to have complex side-effects.

In every case I can think of, the solution is just 'fix typo in configuration file, delete files, and re-run code'.

Also looping in @navonacalarco

**Comment by edickie** [comment]
1) One issue is that the run-script changes can come either from changes to tigrlab_config.yml or project-settings.yml, which are sitting in separate git repos (datman and the individual projects), so that makes it hard to keep track... 

Maybe an (over-engineered) solution would be for the commit id from each repo to be printed into the run scripts as a comment??

2) 

> and changes to files in metadata or whatever are very unlikely to have complex side-effects.

I strongly disagree...one of yesterdays weirdest run script errors seemed to be due to a change in the export-info.csv file...and because our repo was out of date, we had how this happened or for how long it had been happening..

**Comment by josephdviviano** [comment]
Hi Erin, RE: 2)

There were no side effects. Some strange files were inappropriately exported at T1s, which caused some downstream errors later on in the pipeline. If someone had been watching the run logs closely we would have caught this right away.

Furthermore, those files being exported does not interact with any of the other files. It just generates a few files we need to delete. 

Lastly, I don't think anyone actually looks through the `git log` of metadata. It generally just makes sense to just open the file, see why the regexs aren't working for a given file, and fix it on the spot. For most projects the `exportinfo` file is only 15 lines long.

**Comment by DESm1th** [comment]
It's been a while since I looked at the code that generates the run scripts but does it regenerate all of them every time a change in either tigrlab_config or the individual .yml files occurs?

If not, maybe we can add to it to just have an output log that gets a single entry written to it with the changed file's name and the settings changes that were made? It would probably be easier to parse and then we'd only have one thing to commit if anything.

**Comment by josephdviviano** [comment]
@DESm1th That seems like a better solution. I'm still OK with not bothering to version control at all (we don't need to version control everything). I can't see when we would ever want to revert to a previous project state -- we're just version controlling configuration files which are pretty easy to maintain manually.

We should talk about this at our Wed meeting.

**Comment by josephdviviano** [comment]
I think we've resolved this by moving to a configuration file-only solution. They are now all under version control in the datman_config project.
